# Generated by Django 5.1.1 on 2025-04-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_adminpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Childfirst_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Childmiddle_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Childlast_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=20)),
                ('DOB', models.DateField(default=None)),
                ('POB', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('HOB', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True)),
                ('LOB', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=3, null=True)),
                ('Motherfirst_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Mothermiddle_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Motherlast_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Phone_number', models.BigIntegerField()),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('Date', models.DateField(default=None)),
                ('WOB', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('Vaccination', models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Not Vaccinated', 'Not Vaccinated')], default=None, max_length=14)),
                ('NewDate', models.DateField(default=None)),
            ],
        ),
    ]
