# Generated by Django 5.1.1 on 2025-04-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_doctattendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctattendance',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='doctattendance',
            old_name='NewDate',
            new_name='new_date',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='Childfirst_name',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='Childlast_name',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='Childmiddle_name',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='HOB',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='LOB',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='Motherfirst_name',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='Motherlast_name',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='Mothermiddle_name',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='POB',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='Phone_number',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='Vaccination',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='WOB',
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='child_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='child_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='child_middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='mother_first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='mother_last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='mother_middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctattendance',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='doctattendance',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='hob',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='lob',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='pob',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='phone_number',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='vaccination',
            field=models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Not Vaccinated', 'Not Vaccinated')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='wob',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='New Weight'),
        ),
    ]
