# Generated by Django 5.1.1 on 2025-04-22 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_dob_doctattendance_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('child_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('child_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('dob', models.DateField(default=None)),
                ('pob', models.CharField(blank=True, max_length=255, null=True)),
                ('hob', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lob', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mother_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.BigIntegerField(default=None)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=None)),
                ('wob', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='New Weight')),
                ('vaccination', models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Not Vaccinated', 'Not Vaccinated')], default=None, max_length=20)),
                ('new_date', models.DateField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='new_date',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='vaccination',
        ),
        migrations.RemoveField(
            model_name='doctattendance',
            name='wob',
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='Attendance',
            field=models.CharField(choices=[('Attend', 'Attend'), ('Not Attend', 'Not Attend')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.patientreg'),
        ),
    ]
