# Generated by Django 5.1.1 on 2025-04-22 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_doctreport_remove_doctattendance_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('child_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('child_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('dob', models.DateField(default=None)),
                ('pob', models.CharField(blank=True, max_length=255, null=True)),
                ('hob', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lob', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mother_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.BigIntegerField(default=None)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('Notification', models.CharField(choices=[('Unakumbushwa kufika clinic siku ya kesho', 'Unakumbushwa kufika clinic siku ya kesho')], default=None, max_length=100)),
                ('patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.patientreg')),
            ],
        ),
    ]
