# Generated by Django 5.2 on 2025-04-28 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_remove_patientreg_patient_doctattendance_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctattendance',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='doctnotification',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientreg',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.doctnotification'),
        ),
    ]
