# Generated by Django 5.2 on 2025-04-28 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_doctattendance_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientreg',
            old_name='patient',
            new_name='notification',
        ),
        migrations.AddField(
            model_name='patientreg',
            name='attendance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.doctattendance'),
        ),
        migrations.AddField(
            model_name='patientreg',
            name='report',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.doctreport'),
        ),
    ]
