# Generated by Django 5.2 on 2025-04-28 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_rename_patient_patientreg_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreg',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='patientreg',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='patientreg',
            name='report',
        ),
        migrations.AddField(
            model_name='doctattendance',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.patientreg'),
        ),
        migrations.AddField(
            model_name='doctnotification',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.patientreg'),
        ),
        migrations.AddField(
            model_name='doctreport',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.patientreg'),
        ),
    ]
