# Generated by Django 5.2 on 2025-04-28 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_remove_patientreg_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreg',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='App.adminpage'),
        ),
    ]
