# Generated by Django 5.2 on 2025-04-28 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_patientreg_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientReg',
            new_name='ParentReg',
        ),
    ]
