# Generated by Django 5.2 on 2025-04-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_rename_patientreg_parentreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctattendance',
            old_name='patient',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='doctnotification',
            old_name='patient',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='doctreport',
            old_name='patient',
            new_name='parent',
        ),
    ]
